function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
% Generated on: 11-May-2019 15:07:26

persistent Hd;

if isempty(Hd)
    
    N      = 16;    % Order
    Fpass1 = 0.1;     % First Passband Frequency
    Fpass2 = 45;    % Second Passband Frequency
    Apass  = 1;     % Passband Ripple (dB)
    Fs     = 1000;  % Sampling Frequency
    
    h = fdesign.bandpass('n,fp1,fp2,ap', N, Fpass1, Fpass2, Apass, Fs);
    
    Hd = design(h, 'cheby1', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

